#!/bin/sh

model=$(uname -i)
model=${model/AP/}

jetsam_orig_plist="/System/Library/LaunchDaemons/com.apple.jetsamproperties.${model}.plist.bak"
jetsam_plist="/System/Library/LaunchDaemons/com.apple.jetsamproperties.${model}.plist"

if [[ ! -f "${jetsam_orig_plist}" ]];then
    echo "Error: Couldn't find the original jetsam properties plist (${jetsam_orig_plist})"
    exit 1
fi

mv "${jetsam_orig_plist}" "${jetsam_plist}"
echo "Restored the backup file"

killall -9 mDNSResponder || true

function finish() {
	f="${1}"
	[[ -z "${f}" || -z "${CYDIA}" ]] && return
	cydia=(${CYDIA})
	[[ ${cydia[1]} -eq 1 ]] || return
	echo "finish:${f}" >&${cydia[0]}
}

if [[ "$1" == "remove" ]]; then
	finish reboot
fi