#!/bin/sh

model=$(uname -i)
model=${model/AP/}

jetsam_plist="/System/Library/LaunchDaemons/com.apple.jetsamproperties.${model}.plist"

if [[ ! -f "${jetsam_plist}" ]];then
    echo "Error: Couldn't find the jetsam properties plist (${jetsam_plist})"
    exit 1
fi

cp "${jetsam_plist}" "${jetsam_plist/.plist/.plist.bak}"
echo "Created the backup file (${jetsam_plist/.plist/.plist.bak})"

# The new upper memory limit for mDNSResponder
new_limit=384

plutil -key Version4 -key Daemon -key Override -key com.apple.mDNSResponder.reloaded -key ActiveSoftMemoryLimit -value ${new_limit} $jetsam_plist
plutil -key Version4 -key Daemon -key Override -key com.apple.mDNSResponder.reloaded -key InactiveHardMemoryLimit -value ${new_limit} $jetsam_plist

plutil -key Version4 -key System -key Override -key Global -key UserReclaimableLimit -remove $jetsam_plist
plutil -key Version4 -key System -key Override -key Global -key UserHighWaterMark -remove $jetsam_plist
